spring.application.name=api
spring.graphql.graphiql.enabled=true
server.port=${PORT:8080}
server.address=0.0.0.0
server.forward-headers-strategy=native

# GraphQL CORS
spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allowed-headers=*

# Firestore
spring.cloud.gcp.firestore.database-id=waypoints

#spring.cloud.gcp.credentials.location=file:/usr/local/google/home/pwujczyk/github/Home.Configuration/PTProjectsWeb.Firebase.ServiceAccount.json
spring.cloud.gcp.project-id=ptprojectsweb
